name: Release Please Monorepo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release-manual
    steps:
      - name: Mint GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # actions/create-github-app-token@v3.2.0 release: https://github.com/actions/create-github-app-token/releases/tag/v3.2.0
        with:
          client-id: ${{ secrets.RELEASE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write

      - uses: pagopa/eng-cloud-strategy-hub/actions/global/release-please-google@c85a7244fc9478f02175d2a6bde0e8d83f6cb028 # release-please-google@v2.4.0 release: https://github.com/pagopa/eng-cloud-strategy-hub/releases/tag/v2.4.0
        env:
          RELEASE_APP_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          github_token: ${{ env.RELEASE_APP_TOKEN }}
          checkout: "true"
          target_branch: main
          config_file: .github/release/release-please-config.json
          manifest_file: .github/release/.release-please-manifest.json
          auto_merge: "true"
          merge_method: squash
          debug: "true"
