name: Pre-commit

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2 release: https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          persist-credentials: false

      - uses: pagopa/<repo-actions>/actions/global/pre-commit@<sha>
        with:
          pre-commit-image: ghcr.io/antonbabenko/pre-commit-terraform:v1.105.0@sha256:4ef4b8323b27fc263535ad88c9d2f20488fcb3b520258e5e7f0553ed5f6692b5
          pre-commit-config: .pre-commit-config.yaml
          pre-commit-cache-dir: ""
          run-args: --all-files --verbose --show-diff-on-failure --color always
