name: 10 🛂 pre-commit

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2 release: https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          persist-credentials: false

      - name: Restore pre-commit cache
        id: pre-commit-cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5 release: https://github.com/actions/cache/releases/tag/v5.0.5
        with:
          path: ${{ runner.temp }}/pre-commit-cache
          key: pre-commit-${{ runner.os }}-config-hash-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-config-hash-

      - name: Run pre-commit in container
        id: pre-commit-run
        uses: ./actions/global/pre-commit
        with:
          pre-commit-cache-dir: ${{ runner.temp }}/pre-commit-cache

      - name: Save pre-commit cache
        if: ${{ always() && steps.pre-commit-run.outcome != 'skipped' && steps.pre-commit-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5 release: https://github.com/actions/cache/releases/tag/v5.0.5
        with:
          path: ${{ runner.temp }}/pre-commit-cache
          key: pre-commit-${{ runner.os }}-config-hash-${{ hashFiles('.pre-commit-config.yaml') }}
